baseURL = "/"
languageCode = "en-us"
title = "Guru Teg Bahadur Khalsa Institute of Engineering & Technology"
theme = "hugo-serif-theme"

[params]
  google_analytics_id=""



[[menu.main]]
    name = "Mail"
    url = "https://mail.google.com/a/gtb.org.in/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3
